# @package _group_

common:
  fp16: false
  fp16_no_flatten_grads: true
  log_format: json
  log_interval: 100
  reset_logging: false
  suppress_crashes: false
  wandb_project: "eccc"
  # wandb_entity: "indy-lis"
  no_progress_bar: false

checkpoint:
  save_interval: 1000
  save_interval_updates: 1000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: corr
  save_dir: .

distributed_training:
  distributed_world_size: 1

task:
  _name: eccc
  data: ???
  labels: "csv"
  sort_by_length: false
  max_length: null
  target_dictionary: "../dict.txt"

dataset:
  num_workers: 0
  batch_size: 16
  skip_invalid_size_inputs_valid_test: true
  ignore_unused_valid_subsets: true
  valid_subset: valid
  validate_interval: 1000
  validate_interval_updates: 1000

criterion:
  _name: model
  log_keys:
    - corr

optimization:
  max_update: 80000
  lr: [0.00003]
  sentence_avg: true
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: cosine
  warmup_updates: 2000
  warmup_init_lr: 1e-08

model:
  _name: wav2itl

  in_dim: 1024
  dim: 384
  causal: false
  depth: 1
  dropout: 0.1
  bias: false
  out_dim: 69
  nhead: 6
  nhead_t: 1
  conv_pos_dim: 128
  conv_pos_groups: 16
  w_cross_attention: true
  ctc_loss: true
  time_hier_transformer: true
  avg_pool: false
